mock5:
	cargo run --release -- --input /husky/henriksson/atrandi/v8_wgs_mock5_pta/countsketch_mat.csv --output umap_mock5.csv

s2:
	cargo run --release -- --input /husky/henriksson/atrandi/v8_wgs_saliva2_mda/countsketch_mat.csv --output umap_s2.csv
