name: R package install (Linux)

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  install:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: deps::.

      - name: Install Zorn
        run: R CMD INSTALL .
